project_name: "EAGS_SLAM_ScanNetpp"
dataset_name: "scannetpp"
checkpoint_path: null
use_wandb: False
frame_limit: -1 # set to -1 to disable
seed: 0
device: 0
verbose: False

mapping:
  new_submap_every: 100
  map_every: 1
  iterations: 400
  new_submap_iterations: 500
  new_submap_points_num: 400000 
  new_submap_gradient_points_num: 50000 
  new_frame_sample_size: 100000 
  new_points_radius: 0.00000001
  current_view_opt_iterations: 0.4 # What portion of iterations to spend on the current view
  alpha_thre: 0.6
  pruning_thre: 0.5
  submap_using_motion_heuristic: False
  edge_depth_thres: 0.05

tracking:
  gt_camera: False
  w_color_loss: 0.5

  iterations: 300
  cam_rot_lr: 0.002
  cam_trans_lr: 0.01
  early_stop_thre: 0.00005
  early_stop_cnt: 5
  scheduler_factor: 0.95
  scheduler_patience: 5

  odometry_type: "odometer"  # gt, const_speed, odometer
  help_camera_initialization: True 
  init_err_ratio: 50
  filter_alpha: True
  filter_outlier_depth: True
  alpha_thre: 0.98
  soft_alpha: False
  mask_invalid_depth: True
  enable_exposure: False

  vo_setting_file: "vo_settings.yaml"

cam:
  depth_scale: 1000.0

lc: 
  device: 1
  min_similarity: 0.34
  pgo_edge_prune_thres: 0.25
  voxel_size: 0.02
  pgo_max_iterations: 500
  registration:
    method: "gs_reg"
    base_lr: 5.e-3
    min_overlap_ratio: 0.2
  min_interval: 0
  final: False

evaluation:
  save_render: False
