inherit_from: configs/ScanNet/scannet.yaml
data:
  input_path: /mnt/sdb/dataset/scannet/data/scans/scene0059_00/processed
  output_path: output/ScanNet/scene0059
  scene_name: scene0059_00
cam: 
  fx: 577.590698
  fy: 578.729797
  cx: 318.905426
  cy: 242.683609