inherit_from: configs/TUM_RGBD/tum_rgbd.yaml
data:
  input_path: /mnt/sdb/dataset/tum/rgbd/main/dataset/rgbd_dataset_freiburg1_room
  output_path: output/TUM_RGBD/rgbd_dataset_freiburg1_room/
  scene_name: rgbd_dataset_freiburg1_room
  frame_limit: -1 # for debugging, set to -1 to disable
cam: #intrinsic is different per scene in TUM
  H: 480
  W: 640
  fx: 517.306408
  fy: 516.469215
  cx: 318.643040
  cy: 255.313989
  crop_edge: 50
  distortion: [0.262383, -0.953104, -0.005358, 0.002628, 1.163314]
