project_name: "EAGS_SLAM_Replica"
dataset_name: "replica"
checkpoint_path: null
use_wandb: False
frame_limit: -1 # for debugging, set to -1 to disable TODO
seed: 1
device: 0 # use int instead of str as it was used in faiss
verbose: False

mapping:
  new_submap_every: 50
  map_every: 5
  iterations: 100
  new_submap_iterations: 900
  new_submap_points_num: 600000 
  new_submap_gradient_points_num: 50000 
  new_frame_sample_size: -1 
  new_points_radius: 0.0000001
  current_view_opt_iterations: 0.4 # What portion of iterations to spend on the current view
  alpha_thre: 0.6
  pruning_thre: 0.1 
  submap_using_motion_heuristic: True
  edge_depth_thres: 0.05

tracking:
  gt_camera: False
  w_color_loss: 0.95

  iterations: 60
  cam_rot_lr: 0.0002
  cam_trans_lr: 0.002
  early_stop_thre: 0.00005
  early_stop_cnt: 5
  scheduler_factor: 0.95
  scheduler_patience: 5

  odometry_type: "odometer"  # gt, const_speed, odometer
  help_camera_initialization: False # temp option to help const_init
  init_err_ratio: 5
  filter_alpha: False
  filter_outlier_depth: True
  alpha_thre: 0.98
  soft_alpha: True
  mask_invalid_depth: False
  enable_exposure: False

  vo_setting_file: "vo_settings.yaml"

cam:
  H: 680
  W: 1200
  fx: 600.0
  fy: 600.0
  cx: 599.5
  cy: 339.5
  depth_scale: 6553.5

lc: 
  device: 1
  min_similarity: 0.5
  pgo_edge_prune_thres: 0.25
  voxel_size: 0.02
  pgo_max_iterations: 500
  registration:
    method: "gs_reg"
    base_lr: 1.e-3
    min_overlap_ratio: 0.1
    use_render: False
  min_interval: 2
  final: False

evaluation:
  save_render: False
